### ISSUE TITLE
Better Markdown

### ISSUE THREAD

**Issue by manvith12** [manvith12/getting-rejected#31]
Make better markdown in readme, with languages hyperlinked to their program

**Comment by sendhyrama** [comment]
I just created PR for this issue. If you don't mind, could you assign me to this issue and label it as 'hacktoberfest'? Thanks! @manvith12

**Comment by manvith12** [comment]
> I just created PR for this issue. If you don't mind, could you assign me to this issue and label it as 'hacktoberfest'? Thanks! @manvith12   

Thankyou and done
