### ISSUE TITLE
[FEAT]: Add dart, scala, elixir, pascal language

### ISSUE THREAD

**Issue by sendhyrama** [manvith12/getting-rejected#8]
### Task list:
- [x] Dart
- [x] Scala
- [x] Elixir
- [x] Pascal

**Comment by sendhyrama** [comment]
Can you add 'hacktoberfest' label to this issue and assign to me? @manvith12

**Comment by manvith12** [comment]
> Can you add 'hacktoberfest' label to this issue and assign to me? @manvith12

it isnt required to have hacktoberfest labelled to get your PR, but ok
